spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: dima2899@gmail.com
    password: shgttohujbonvaqx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
    test-connection: false
    protocol: smtp
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
email-service:
  recipient: creeper.super99@gmail.com
joke-service:
  url: https://official-joke-api.appspot.com/random_joke
translation-service:
  url: https://deep-translate1.p.rapidapi.com/language/translate/v2
  rapid-key: 70e8b7f1aamsha82487dfb0190b6p13ccc7jsn2afff2bb4a75
  rapid-host: deep-translate1.p.rapidapi.com
  target-language: ru
